In [16]:
import matplotlib.pyplot as plt
import numpy as np
import uncertainties.unumpy as unp
from scipy.optimize import curve_fit
from uncertainties import ufloat
import csv

In [17]:
import pandas as pd

In [18]:
import seaborn as sns

sns.set(style="darkgrid")
sns.set_palette("magma")
#Masse Probe in kg
m = 0.342
#Molmasse Kupfer in kg/mol
M = 0.06355
#Kompressionsmodul Kupfer in GPa
k = 140
#Molvolumen Kupfer in m^3/mol
V = 7.11 * 10**-6
#Universelle Gaskonstante
R = 8.31439

In [19]:
t, R_P, R_G, U, I = np.genfromtxt("daten_neu.csv", delimiter=",", skip_header=3, unpack=True,encoding='latin-1')
anzahlDaten = t.size
R_P.size

93

In [20]:
#Bei der Messung wurde der Komma falsch platziert. Dafür wird korrigiert
R_P = R_P*0.1
R_G = R_G*0.1
#Widerstände in Temperatur umrechnen und in K umrechnen mit 0 als Fehler
T_P = 0.00134 * (R_P * 1000)**2 + 2.296 * (R_P * 1000) - 243.02 + 273.15
T_G = 0.00134 * (R_G * 1000)**2 + 2.296 * (R_G * 1000) - 243.02 + 273.15

In [21]:
T = (T_P + T_G) / 2
fehlerT = 0.002*T 
T2 = unp.uarray(T,fehlerT)

In [24]:
U2 = unp.uarray(U, U*0.1)
I2 = unp.uarray(I, I*0.1)
t2 = unp.uarray(t, 5)

array([85.65209349999996+/-0.17130418699999994,
       86.24254199999997+/-0.17248508399999996,
       87.18767499999997+/-0.17437534999999996,
       88.36942959999996+/-0.17673885919999993,
       89.55159959999997+/-0.17910319919999995,
       91.44509499999997+/-0.18289018999999992,
       92.74607829999997+/-0.18549215659999993,
       94.52298479999996+/-0.18904596959999992,
       96.41911999999996+/-0.19283823999999994,
       98.19850549999997+/-0.19639701099999993,
       99.97945879999996+/-0.19995891759999992,
       101.76197989999997+/-0.20352395979999996,
       103.66516349999996+/-0.20733032699999993,
       105.80810429999995+/-0.2116162085999999,
       107.71498629999998+/-0.21542997259999996,
       110.22063819999997+/-0.22044127639999994,
       112.37082839999997+/-0.22474165679999994,
       114.52329659999997+/-0.22904659319999993,
       116.31872189999996+/-0.23263744379999993,
       117.87559599999994+/-0.2357511919999999,
       118.95358549999996+/-0.23790717099999992,
       119.67274989999997+/-0.23934549979999994,
       120.51221499999997+/-0.24102442999999996,
       121.59220109999995+/-0.24318440219999993,
       122.55265029999998+/-0.24510530059999996,
       123.63374859999996+/-0.24726749719999994,
       124.59517599999997+/-0.24919035199999995,
       125.79755319999997+/-0.25159510639999993,
       127.24108119999997+/-0.25448216239999993,
       128.68539979999997+/-0.2573707995999999,
       130.37159279999997+/-0.2607431855999999,
       132.17984189999999+/-0.26435968379999997,
       133.98965879999997+/-0.26797931759999993,
       136.04267669999996+/-0.2720853533999999, 138.58144+/-0.27716288,
       141.24432299999995+/-0.2824886459999999,
       143.7892503+/-0.2875785006,
       146.45881989999998+/-0.29291763979999996,
       149.49599159999997+/-0.2989919831999999,
       152.6591992+/-0.30531839839999997,
       155.82696279999996+/-0.31165392559999994,
       158.63291309999997+/-0.31726582619999993,
       161.197726+/-0.32239545199999997,
       163.76528589999998+/-0.32753057179999995,
       166.09089099999994+/-0.33218178199999987,
       168.29631599999996+/-0.33659263199999995,
       170.50397879999997+/-0.34100795759999997,
       172.71405359999994+/-0.3454281071999999,
       175.17262239999997+/-0.35034524479999996,
       177.3878428+/-0.3547756856,
       179.60547519999994+/-0.3592109503999999,
       182.07181599999996+/-0.36414363199999994,
       184.91081069999996+/-0.3698216213999999,
       187.87644429999997+/-0.37575288859999995,
       191.46441839999997+/-0.38292883679999995,
       195.43045999999998+/-0.39086091999999995,
       199.15529719999995+/-0.3983105943999999,
       202.88640559999996+/-0.4057728111999999,
       206.74842749999996+/-0.41349685499999994,
       210.11742779999997+/-0.42023485559999996,
       213.24129749999997+/-0.42648259499999996,
       216.36909339999997+/-0.4327381867999999,
       219.37566399999997+/-0.43875132799999994,
       222.0095539+/-0.4440191078, 224.39523119999998+/-0.4487904624,
       227.16059739999994+/-0.4543211947999999,
       229.29981749999996+/-0.45859963499999995,
       231.4411414+/-0.4628822828,
       233.96285099999994+/-0.4679257019999999,
       235.98231979999994+/-0.4719646395999999,
       238.63503669999997+/-0.47727007339999994,
       242.0493022+/-0.4840986044, 245.59521819999998+/-0.4911904364,
       248.892935+/-0.49778587, 253.0854455+/-0.506170891,
       256.39369469999997+/-0.5127873893999999,
       259.19627269999995+/-0.5183925453999999, 261.874463+/-0.523748926,
       264.3001527+/-0.5286003054, 266.8562735+/-0.533712547,
       268.90321229999995+/-0.5378064245999999,
       271.46423749999997+/-0.542928475,
       274.15614939999995+/-0.5483122987999999,
       276.46594699999997+/-0.552931894,
       278.90634989999995+/-0.5578126997999999,
       281.6064492+/-0.5632128984, 284.4380248+/-0.5688760496,
       287.91738749999996+/-0.5758347749999999,
       291.0145286999999+/-0.5820290573999999,
       293.9863308+/-0.5879726616000001, 297.2205763+/-0.5944411526,
       299.03362709999993+/-0.5980672541999998,
       300.0713407+/-0.6001426814], dtype=object)

In [23]:
df = pd.DataFrame({"t":t,"R_P":R_P, "R_G": R_G, "T_P":T_P, "T_G":T_G})
df

        t     R_P     R_G         T_P         T_G
0     0.0  0.0243  0.0234   86.714057   84.590130
1     1.5  0.0248  0.0234   87.894954   84.590130
2     3.0  0.0255  0.0235   89.549335   84.826015
3     4.5  0.0262  0.0238   91.205030   85.533830
4     6.0  0.0268  0.0242   92.625242   86.477958
..    ...     ...     ...         ...         ...
88  132.0  0.1070  0.1069  291.143660  290.885397
89  133.5  0.1080  0.1082  293.727760  294.244902
90  135.0  0.1092  0.1095  296.832218  297.608935
91  136.5  0.1103  0.1098  299.681361  298.385894
92  138.0  0.1114  0.1095  302.533746  297.608935

[93 rows x 5 columns]